//! SQL migration using SeaORM Schema API.
//!
//! Migrations generate DDL programmatically from EntityModel-derived entities
//! where possible, falling back to raw SQL for tables without SeaORM entities.
//! A `_schema_version` table tracks which migrations have been applied.

use sea_orm::{ConnectionTrait, DatabaseConnection, Schema};
use sea_orm::Statement;

use crate::error::Error;

use crb_types::{
    agent::AgentSessionEntity,
    benchmark::{
        golden::GoldenCommentEntity,
        judge::JudgeVerdictEntity,
        result::PrResultEntity,
        standalone::BenchmarkEntity,
    },
    finding::FindingEntity,
    review::ReviewEntity,
};

const CURRENT_VERSION: i32 = 1;

/// Create the `_schema_version` tracking table if it does not exist.
async fn create_schema_version_table(db: &DatabaseConnection) -> Result<(), Error> {
    db.execute_unprepared(
        "CREATE TABLE IF NOT EXISTS _schema_version (
            version     INTEGER PRIMARY KEY,
            applied_at  TEXT NOT NULL DEFAULT (datetime('now')),
            description TEXT
        );",
    )
    .await
    .map_err(|e| Error::Migration(format!("failed to create _schema_version table: {e}")))?;
    Ok(())
}

/// Get the current schema version from the database.
/// Returns 0 if no migrations have been applied yet.
async fn get_current_version(db: &DatabaseConnection) -> Result<i32, Error> {
    let sql = "SELECT COALESCE(MAX(version), 0) FROM _schema_version;".to_string();
    let result = db
        .query_one_raw(sea_orm::Statement::from_string(
            db.get_database_backend(),
            sql,
        ))
        .await
        .map_err(|e| Error::Migration(format!("failed to query schema version: {e}")))?;

    match result {
        Some(row) => {
            let version: i32 = row.try_get_by_index::<i32>(0).unwrap_or(0);
            Ok(version)
        }
        None => Ok(0),
    }
}

/// Run all pending migrations against the given database connection.
///
/// Creates the `_schema_version` table if it does not exist, then applies
/// any migration whose version is greater than the current schema version.
///
/// This function is idempotent and safe to call multiple times.
pub async fn run_migrations(db: &DatabaseConnection) -> Result<(), Error> {
    create_schema_version_table(db).await?;

    let current_version = get_current_version(db).await?;

    if current_version < CURRENT_VERSION {
        migrate_v1(db).await?;
    }

    Ok(())
}

/// Version 1: Initial schema — create all tables.
async fn migrate_v1(db: &DatabaseConnection) -> Result<(), Error> {
    let schema = Schema::new(db.get_database_backend());

    // ------------------------------------------------------------------
    // 1. Create tables from EntityModel-derived entities
    // ------------------------------------------------------------------
    create_entity_table(db, BenchmarkEntity, &schema).await?;
    create_entity_table(db, ReviewEntity, &schema).await?;
    create_entity_table(db, PrResultEntity, &schema).await?;
    create_entity_table(db, GoldenCommentEntity, &schema).await?;
    create_entity_table(db, FindingEntity, &schema).await?;
    create_entity_table(db, JudgeVerdictEntity, &schema).await?;
    create_entity_table(db, AgentSessionEntity, &schema).await?;

    // ------------------------------------------------------------------
    // 2. Add extra columns not covered by EntityModel
    //    (the EntityModel-derived entity for AgentSession only has `id`;
    //     the store writes `review_id` and `model_name` via raw SQL)
    // ------------------------------------------------------------------
    add_column_if_not_exists(db, "agent_sessions", "review_id", "TEXT NOT NULL DEFAULT ''")
        .await?;
    add_column_if_not_exists(db, "agent_sessions", "model_name", "TEXT NOT NULL DEFAULT ''")
        .await?;

    // ------------------------------------------------------------------
    // 3. Enable foreign keys and add CASCADE for entity-created tables
    // ------------------------------------------------------------------
    db.execute_unprepared("PRAGMA foreign_keys = ON;").await
        .map_err(|e| Error::Migration(e.to_string()))?;

    // Add CASCADE ON DELETE for pr_results FKs (not generated by Schema API)
    // SQLite requires recreating the table — instead, handle cascade in the Store impl

    // Drop the old `judged_findings` table (empty, never populated)
    db.execute_unprepared("DROP TABLE IF EXISTS judged_findings;")
        .await
        .map_err(|e| Error::Migration(e.to_string()))?;

    // ------------------------------------------------------------------
    // 4. Create non-entity tables via raw SQL
    // ------------------------------------------------------------------
    create_raw_table(
        db,
        &format!(
            "CREATE TABLE IF NOT EXISTS agent_turns (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id  TEXT NOT NULL,
                turn_index  INTEGER NOT NULL,
                UNIQUE(session_id, turn_index)
            );"
        ),
    )
    .await?;

    create_raw_table(
        db,
        &format!(
            "CREATE TABLE IF NOT EXISTS agent_turn_messages (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                turn_id         INTEGER NOT NULL,
                msg_index       INTEGER NOT NULL,
                role            TEXT NOT NULL DEFAULT 'user',
                text_content    TEXT,
                thinking        TEXT,
                output          TEXT,
                tool_name       TEXT,
                tool_input      TEXT,
                tool_output     TEXT,
                UNIQUE(turn_id, msg_index)
            );"
        ),
    )
    .await?;

    create_raw_table(
        db,
        &format!(
            "CREATE TABLE IF NOT EXISTS agent_session_usages (
                agent_session_id            TEXT PRIMARY KEY NOT NULL,
                input_tokens                INTEGER NOT NULL DEFAULT 0,
                output_tokens               INTEGER NOT NULL DEFAULT 0,
                cached_input_tokens         INTEGER NOT NULL DEFAULT 0,
                cache_creation_input_tokens INTEGER NOT NULL DEFAULT 0,
                reasoning_tokens            INTEGER NOT NULL DEFAULT 0,
                tool_use_prompt_tokens      INTEGER NOT NULL DEFAULT 0,
                call_count                  INTEGER NOT NULL DEFAULT 0,
                tool_use_count              INTEGER NOT NULL DEFAULT 0
            );"
        ),
    )
    .await?;

    create_raw_table(
        db,
        &format!(
            "CREATE TABLE IF NOT EXISTS cache_usage_entries (
                agent_session_id    TEXT PRIMARY KEY NOT NULL,
                cache_hits          INTEGER NOT NULL DEFAULT 0,
                cache_misses        INTEGER NOT NULL DEFAULT 0
            );"
        ),
    )
    .await?;

    // ------------------------------------------------------------------
    // 4. Indexes
    // ------------------------------------------------------------------
    let indexes = [
        "CREATE INDEX IF NOT EXISTS idx_golden_comments_pr ON golden_comments(pr_result_id);",
        "CREATE INDEX IF NOT EXISTS idx_findings_pr ON findings(pr_result_id);",
        "CREATE INDEX IF NOT EXISTS idx_agent_sessions_review ON agent_sessions(review_id);",
        "CREATE INDEX IF NOT EXISTS idx_agent_turns_session ON agent_turns(session_id);",
        "CREATE INDEX IF NOT EXISTS idx_agent_turn_messages_turn ON agent_turn_messages(turn_id);",
        "CREATE INDEX IF NOT EXISTS idx_reviews_status ON reviews(status);",
    ];
    for stmt in indexes {
        db.execute_unprepared(stmt)
            .await
            .map_err(|e| Error::Migration(format!("failed to create index: {e}")))?;
    }

    // ------------------------------------------------------------------
    // 5. Record version
    // ------------------------------------------------------------------
    db.execute_unprepared(
        "INSERT INTO _schema_version (version, description) VALUES (1, 'initial schema')",
    )
    .await
    .map_err(|e| Error::Migration(format!("failed to record schema version: {e}")))?;

    Ok(())
}

/// Create a table from a SeaORM EntityModel-derived entity, using
/// `CREATE TABLE IF NOT EXISTS` for idempotency.
async fn create_entity_table<E>(db: &DatabaseConnection, entity: E, schema: &Schema) -> Result<(), Error>
where
    E: sea_orm::EntityTrait + Send + Sync,
{
    let stmt = schema.create_table_from_entity(entity);
    let backend = db.get_database_backend();
    let statement = backend.build(&stmt);
    let sql = statement.to_string();
    let ddl = sql.replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ");

    db.execute_unprepared(&ddl)
        .await
        .map_err(|e| Error::Migration(format!("failed to create entity table: {e}")))?;

    Ok(())
}

/// Add a column to an existing table, silently skipping if it already exists.
/// SQLite does not support `ALTER TABLE ... ADD COLUMN IF NOT EXISTS`, so we
/// catch the "duplicate column name" error.
async fn add_column_if_not_exists(
    db: &DatabaseConnection,
    table: &str,
    column: &str,
    col_type: &str,
) -> Result<(), Error> {
    let sql = format!("ALTER TABLE {table} ADD COLUMN {column} {col_type}");
    match db.execute_unprepared(&sql).await {
        Ok(_) => Ok(()),
        Err(e) => {
            let msg = e.to_string().to_lowercase();
            if msg.contains("duplicate column") {
                Ok(())
            } else {
                Err(Error::Migration(format!(
                    "failed to add column {column} to {table}: {e}"
                )))
            }
        }
    }
}

/// Execute a raw SQL string to create a table.
async fn create_raw_table(db: &DatabaseConnection, sql: &str) -> Result<(), Error> {
    db.execute_unprepared(sql)
        .await
        .map_err(|e| Error::Migration(format!("failed to create table: {e}")))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_current_version_is_valid() {
        assert!(CURRENT_VERSION > 0, "CURRENT_VERSION must be positive");
    }

    /// Smoke test: verify all migrations run against an in-memory database.
    #[tokio::test]
    async fn test_migration_runs_successfully() {
        let db: DatabaseConnection = sea_orm::Database::connect("sqlite::memory:")
            .await
            .expect("failed to open in-memory database");

        run_migrations(&db).await.expect("migration should succeed");

        // Verify the schema version was recorded
        let version = get_current_version(&db).await.unwrap();
        assert_eq!(
            version, CURRENT_VERSION,
            "schema version should match current version"
        );

        // Verify tables exist by querying sqlite_master
        let tables = [
            "reviews",
            "benchmarks",
            "pr_results",
            "findings",
            "judge_verdicts",
            "golden_comments",
            "agent_sessions",
            "agent_turns",
            "agent_turn_messages",
            "agent_session_usages",
            "cache_usage_entries",
            "_schema_version",
        ];
        for name in &tables {
            let row = db
                .query_one_raw(sea_orm::Statement::from_string(
                    db.get_database_backend(),
                    format!(
                        "SELECT count(*) FROM sqlite_master WHERE type='table' AND name='{name}'"
                    ),
                ))
                .await
                .expect("query should succeed");
            let count: i32 = row.and_then(|r| r.try_get_by_index::<i32>(0).ok()).unwrap_or(0);
            assert_eq!(
                count, 1,
                "table '{name}' should exist after migration"
            );
        }

        // Verify the migration is idempotent
        run_migrations(&db).await.expect("second run should succeed");
        let version = get_current_version(&db).await.unwrap();
        assert_eq!(
            version, CURRENT_VERSION,
            "version should remain unchanged after re-run"
        );
    }
}
