#[cfg(feature = "seaorm-storage")]
use mti::prelude::MagicTypeId;

/// Assign a MagicTypeId parent PK to a child FK field.
///
/// Generated Save code uses this trait so that child FK fields of different
/// types (MagicTypeId, String, Option<String>, etc.) all accept the parent PK
/// without orphan-rule violations.
#[cfg(feature = "seaorm-storage")]
pub trait FkFromMagicTypeId {
    fn from_mtid(pk: &MagicTypeId) -> Self;
}

#[cfg(feature = "seaorm-storage")]
impl FkFromMagicTypeId for MagicTypeId {
    fn from_mtid(pk: &MagicTypeId) -> Self {
        pk.clone()
    }
}

#[cfg(feature = "seaorm-storage")]
impl FkFromMagicTypeId for Option<MagicTypeId> {
    fn from_mtid(pk: &MagicTypeId) -> Self {
        Some(pk.clone())
    }
}

#[cfg(feature = "seaorm-storage")]
impl FkFromMagicTypeId for String {
    fn from_mtid(pk: &MagicTypeId) -> Self {
        pk.to_string()
    }
}

#[cfg(feature = "seaorm-storage")]
impl FkFromMagicTypeId for Option<String> {
    fn from_mtid(pk: &MagicTypeId) -> Self {
        Some(pk.to_string())
    }
}

/// Trait for domain structs that have a surrogate primary key.
///
/// Auto-implemented by `#[derive(EntityModel)]`. The `Id` associated type
/// is the unwrapped PK type (e.g. `i32` for `Option<i32>`, `MagicTypeId`
/// for non-Option PKs).
pub trait EntityId {
    type Id: Clone;
    fn get_id(&self) -> Option<Self::Id>;
}

/// Trait for domain structs that can persist themselves to the DB.
///
/// Auto-implemented by `#[derive(EntityModel)]` for structs with no flatten or ignored fields.
#[cfg(feature = "seaorm-storage")]
#[trait_variant::make(Send)]
pub trait Save {
    /// Save this entity.
    async fn save(&self, db: &sea_orm::DatabaseConnection) -> Result<(), anyhow::Error>;
}

/// Flat entity loading — model row → domain struct, no children.
///
/// Auto-generated by `#[derive(EntityModel)]` for ALL types unconditionally.
#[cfg(feature = "seaorm-storage")]
#[trait_variant::make(Send)]
pub trait EntityLoader: Sized {
    /// Load a single entity by its primary key.
    async fn load_by_id(
        db: &sea_orm::DatabaseConnection,
        id: &MagicTypeId,
    ) -> Result<Option<Self>, anyhow::Error>;

    /// Load all entities (shallow, no children).
    async fn load_all(db: &sea_orm::DatabaseConnection) -> Result<Vec<Self>, anyhow::Error>;
}

/// Recursive child hydration.
///
/// Auto-generated by `#[derive(EntityModel)]` for types with `has_many`,
/// `has_one`, or hydratable `ignore` fields.
#[cfg(feature = "seaorm-storage")]
#[trait_variant::make(Send)]
pub trait LoadChildren: Sized {
    /// Hydrate this entity's children (direct children for `Shallow`, full tree for `Deep`).
    ///
    /// Implementations should load children from the database according to `depth`.
    /// Types with no child relations should simply return `Ok(())`.
    async fn load_children(
        &mut self,
        db: &sea_orm::DatabaseConnection,
        depth: LoadDepth,
    ) -> Result<(), anyhow::Error>;
}

/// Depth control for recursive child loading.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LoadDepth {
    /// Load only the immediate children (one level deep).
    Shallow,
    /// Recursively load the full reachable tree.
    Deep,
}

impl Default for LoadDepth {
    fn default() -> Self {
        Self::Deep
    }
}
