[package]
name = "riv-webui-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[features]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]
hydrate = ["leptos/hydrate"]

[dependencies]
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
lucide-leptos = { workspace = true, features = ["all-icons"] }
mti = { workspace = true }
serde = { workspace = true }
riv-types = { path = "../riv-types" }
riv-webui-shared = { path = "../riv-webui-shared" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures = { workspace = true }
gloo-net = { workspace = true }
gloo-timers = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
web-sys = { workspace = true, features = ["Element", "EventSource", "HtmlElement", "MessageEvent", "Window"] }
wasm-bindgen = { workspace = true }

[lints]
workspace = true
