[package]
name = "riv-stor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["sqlite"]
sqlite = []

[dependencies]
riv-types = { path = "../riv-types", features = ["seaorm-storage"] }
mti = { workspace = true }
sea-orm = { workspace = true, features = [
  "macros",
  "sqlx-sqlite",
  "runtime-tokio",
  "chrono",
  "entity-registry",
  "schema-sync",
] }
serde = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
