[package]
name = "riv-benchmark"
autolib = false
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "riv-benchmark"
path = "src/main.rs"
required-features = ["binary"]

[lib]
name = "riv_benchmark"
path = "src/lib.rs"

[features]
deafult = ["riv-shared/backend"]
binary = ["dep:clap", "dep:riv-harness", "dep:riv-rules", "dep:riv-tools", "dep:dotenvy","dep:serde", "dep:strum", "dep:tracing-subscriber"]

[dependencies]
anyhow = { workspace = true }
riv-agents = { path = "../riv-agents" }
riv-cache = { path = "../riv-cache" }
riv-reporting = { path = "../riv-reporting" }
riv-shared = { path = "../riv-shared" }
riv-types = { path = "../riv-types" }
mti = { workspace = true }
rig-core = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync"] }

# Binary Dependencies
clap = { workspace = true, optional = true }
riv-harness = { path = "../riv-harness", optional = true }
riv-rules = { path = "../riv-rules", optional = true }
riv-tools = { path = "../riv-tools", optional = true }
dotenvy = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
strum = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
