use mti::prelude::MagicTypeId;
use serde::{Deserialize, Serialize};

use crate::wrappers::Model;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSession {
    /// The unique ID of the agent session.
    pub id: MagicTypeId,

    /// The model used for this agent session.
    pub model: Model,

    /// A list of turns the agent has taken in this session.
    ///
    /// Each turn is an ordered list of [`RoleMessage`]'s,
    /// which can be either user messages, tool messages, or assistant messages.
    pub turns: Vec<Vec<RoleMessage>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RoleMessage {
    /// A message from the user to the agent.
    User(String),

    /// A complete tool invocation.
    Tool(ToolInvocation),

    /// A response generated by the agent.
    Assistant(AgentResponse),

    /// A system prompt.
    System(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolInvocation {
    /// The Name of the tool.
    pub tool_name: String,

    /// The generated input json from the LLM.
    pub input: serde_json::Value,

    /// The output json result from the tool.
    pub output: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResponse {
    /// The LLMs internal thinking for this response.
    pub thinking: String,

    /// The final output generated by the LLM.
    pub output: String,
}

/// A chunk of an agent session, used for streaming responses of partial data.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AgentChunk {
    Thinking {
        /// The ID of the [`AgentSession`] this chunk belongs to.
        id: MagicTypeId,

        /// The content of the thinking chunk.
        content: String,

        /// Indiciates whether this is the last chunk of this turn.
        last: bool,
    },
    Output {
        /// The ID of the [`AgentSession`] this chunk belongs to.
        id: MagicTypeId,

        /// The content of the output chunk.
        content: String,

        /// Indiciates whether this is the last chunk of this turn.
        last: bool,
    },
    Tool {
        /// The ID of the [`AgentSession`] this chunk belongs to.
        id: MagicTypeId,

        /// The Tool Invocation ID this chunk belongs to.
        invocation_id: String,

        /// A byte of the tool chunk.
        byte: ToolByte,

        /// Indiciates whether this is the last chunk of this turn.
        last: bool,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ToolByte {
    /// Mark the beginning of the tool invocation.
    ///
    /// Contains the tool name
    Begin(String),

    /// A single bit of the tool invocation from the agent.
    ///
    /// Contains the streamed chunk of the tool invocation.
    Bit(String),

    /// Mark the end of the tool invocation.
    End,

    /// The final result(s) of the tool invocation.
    Result(Vec<String>),
}
