use mti::prelude::MagicTypeId;

/// Trait for domain structs that have a surrogate primary key.
///
/// Auto-implemented by `#[derive(EntityModel)]`. The `Id` associated type
/// is the unwrapped PK type (e.g. `i32` for `Option<i32>`, `MagicTypeId`
/// for non-Option PKs).
pub trait EntityId {
    type Id: Clone;
    fn get_id(&self) -> Option<Self::Id>;
}

/// Trait for domain structs that can persist themselves to the DB.
///
/// Auto-implemented by `#[derive(EntityModel)]` for structs with no flatten or ignored fields.
#[cfg(feature = "seaorm-storage")]
#[allow(async_fn_in_trait)]
pub trait Save {
    async fn save(&self, db: &sea_orm::DatabaseConnection) -> Result<(), anyhow::Error>
    where
        Self: Send + Sync;
}

/// Flat entity loading — model row → domain struct, no children.
///
/// Auto-generated by `#[derive(EntityModel)]` for ALL types unconditionally.
#[cfg(feature = "seaorm-storage")]
#[allow(async_fn_in_trait)]
pub trait EntityLoader: Sized {
    /// Load a single entity by its primary key.
    async fn load_by_id(
        db: &sea_orm::DatabaseConnection,
        id: &MagicTypeId,
    ) -> Result<Option<Self>, anyhow::Error>;

    /// Load all entities (shallow, no children).
    async fn load_all(db: &sea_orm::DatabaseConnection) -> Result<Vec<Self>, anyhow::Error>;
}

/// Recursive child hydration.
///
/// Auto-generated by `#[derive(EntityModel)]` for types with `has_many`,
/// `has_one`, or hydratable `ignore` fields.
#[cfg(feature = "seaorm-storage")]
#[allow(async_fn_in_trait)]
pub trait LoadChildren: Sized {
    /// Hydrate this entity's children (direct children for `Shallow`, full tree for `Deep`).
    ///
    /// Default impl is a no-op. Entities with HasMany/HasOne relations override this
    /// to load children from the database.
    async fn load_children(
        &mut self,
        _db: &sea_orm::DatabaseConnection,
        _depth: LoadDepth,
    ) -> Result<(), anyhow::Error> {
        Ok(())
    }

    /// Convenience: hydrate full tree. Equivalent to `load_children(db, LoadDepth::Deep)`.
    async fn ensure_fully_hydrated(
        &mut self,
        db: &sea_orm::DatabaseConnection,
    ) -> Result<(), anyhow::Error> {
        self.load_children(db, LoadDepth::Deep).await
    }

    /// Batch-hydrate children for many entities (avoids N+1).
    /// Default impl loops per-entity; types with N+1-sensitive relationships override.
    async fn load_children_batch(
        entities: &mut [Self],
        db: &sea_orm::DatabaseConnection,
        depth: LoadDepth,
    ) -> Result<(), anyhow::Error> {
        for e in entities {
            e.load_children(db, depth).await?;
        }
        Ok(())
    }
}

/// Depth control for recursive child loading.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LoadDepth {
    /// Load only the immediate children (one level deep).
    Shallow,
    /// Recursively load the full reachable tree.
    Deep,
}

impl Default for LoadDepth {
    fn default() -> Self {
        Self::Deep
    }
}
